### PR TITLE
Use newer language features

### PR DESCRIPTION
**Pull request by craigp**
Optionally use some newer language features, and change the application
to use the newer supervisor spec and avoid the warnings.

### CODE REVIEW

**Comment by Sinc63** [comment]
Consider changing the project version so if someone installs your version it doesn't look like the base one.

**Comment by OvermindDL1** [comment]
Looks good, sorry for the delay, wasn't getting github notifications there for a long time, though thankfully that recent message today has popped it back!

**Comment by OvermindDL1** [comment]
And published as 0.2 due to technically backwards incompatible change (new base elixir version).

**Comment by Sinc63** [comment]
Glad I could tweak a notification. One dependency down, 17 more to get upgraded to allow my Elixir 1.7 to 1.13 upgrade to not generate warnings.

**Pull request merged**
